### ISSUE TITLE
HaranoAjiFonts CN, TW, K1の括弧類

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFontsCN#1]
お世話になります。
HaranoAji CN, TW, K1 の縦組みの括弧類について不明な点が出てきたので質問します。
ちなみに横組みの括弧類は期待通りの動作をしています。
ソースは後ろの方に記載しています。

1. CNのU+2018..2019, U+201C..201D がカギ括弧に化けているように見えますが、意図的でしょうか?
2. CNとTWのU+301D..301Eがまともでないように見えるのはやむを得ない?
3. TWのU+FE59..FE5Eがまともでないように見えるのはやむを得ない?
4. K1のU+3016..3019がまともでないように見えるのはやむを得ない?

![image](https://user-images.githubusercontent.com/3814120/153756208-237eab34-3050-4d1a-9177-965c1a7e82b7.png)

私の作ったvfの方で失敗している可能性もあります。原因の切り分けができていない点は済みません。
CKのvfの作成にはmakejvfを使っていますが特殊なオプション(ミニュート置き換えなど)は使わない設定になっているはずです。
開発中のvfのソースは↓こちら
https://github.com/t-tk/japanese-otf-uptex/tree/ck-basefont

dvipdfmx のオプション `-l` landscape を使用。
```
\documentclass[landscape]{utarticle}

%\usepackage[uplatex]{otf}
\AtBeginDvi{\special{pdf:mapline uphminr-v unicode HaranoAjiMincho-Medium.otf -w 1}}
\AtBeginDvi{\special{pdf:mapline upaschminr-v unicode HaranoAjiMinchoCN-Medium.otf -w 1}}
\AtBeginDvi{\special{pdf:mapline upatchminr-v unicode HaranoAjiMinchoTW-Medium.otf -w 1}}
\AtBeginDvi{\special{pdf:mapline upakorminr-v unicode HaranoAjiMinchoK1-Medium.otf -w 1}}

\font\upjpnrmm = upnmlminr-v at 10.0pt
\font\upschrmm = upnmschminr-v at 10.0pt
\font\uptchrmm = upnmtchminr-v at 10.0pt
\font\upkorrmm = upnmkorminr-v at 10.0pt

\begin{document}
\parindent0mm

\section{日本語}
\upjpnrmm

=\kchar"00AB回\kchar"00BB% U+00AB, U+00BBは width: Neutralなのでずれても不思議ではない。
=\kchar"2018回\kchar"2019=\kchar"201C回\kchar"201D=\kchar"2329回\kchar"232A=\kchar"3008回\kchar"3009%
=\kchar"300A回\kchar"300B=\kchar"300C回\kchar"300D=\kchar"300E回\kchar"300F=\kchar"3010回\kchar"3011=\\
=\kchar"3014回\kchar"3015=\kchar"3016回\kchar"3017=\kchar"3018回\kchar"3019%
=\kchar"301D回\kchar"301E=\kchar"301D回\kchar"301F%
=\kchar"FF08回\kchar"FF09=\kchar"FF3B回\kchar"FF3D=\kchar"FF5B回\kchar"FF5D=\kchar"FF5F回\kchar"FF60=


\section{中国語簡体字}
\upschrmm

=\kchar"2018回\kchar"2019=\kchar"201C回\kchar"201D=\kchar"2329回\kchar"232A=\kchar"3008回\kchar"3009%
=\kchar"300A回\kchar"300B=\kchar"300C回\kchar"300D=\kchar"300E回\kchar"300F=\kchar"3010回\kchar"3011=\\
=\kchar"3014回\kchar"3015=\kchar"3016回\kchar"3017=\kchar"301D回\kchar"301E%
=\kchar"FF08回\kchar"FF09=\kchar"FF3B回\kchar"FF3D=\kchar"FF5B回\kchar"FF5D=

\section{中国語繁体字}
\uptchrmm

=\kchar"2018回\kchar"2019=\kchar"201C回\kchar"201D=\kchar"2329回\kchar"232A=\kchar"3008回\kchar"3009%
=\kchar"300A回\kchar"300B=\kchar"300C回\kchar"300D=\kchar"300E回\kchar"300F=\kchar"3010回\kchar"3011=\\
=\kchar"3014回\kchar"3015=\kchar"301D回\kchar"301E=\kchar"FE59回\kchar"FE5A=\kchar"FE5B回\kchar"FE5C%
=\kchar"FE5D回\kchar"FE5E=\kchar"FF08回\kchar"FF09=\kchar"FF3B回\kchar"FF3D=\kchar"FF5B回\kchar"FF5D=

\section{韓国語}
\upkorrmm

=\kchar"2018믐\kchar"2019=\kchar"201C믐\kchar"201D=\kchar"3008믐\kchar"3009%
=\kchar"300A믐\kchar"300B=\kchar"300C믐\kchar"300D=\kchar"300E믐\kchar"300F=\kchar"3010믐\kchar"3011=\\
=\kchar"3014믐\kchar"3015=\kchar"3016믐\kchar"3017=\kchar"3018믐\kchar"3019%
=\kchar"FF08믐\kchar"FF09=\kchar"FF3B믐\kchar"FF3D=\kchar"FF5B믐\kchar"FF5D=

\end{document}

```

**Comment by trueroad** [comment]
vf の問題か否かの切り分け、原ノ味の問題か SourceHan の問題かの切り分けのため、本コメント末尾につけた plain XeTeX ソースで確認をしてみました。
（XeTeX ですので日本語組版とか縦組みとかではおかしいところがありますが OpenType フォントのグリフ選択は正しいものと認識しております。）

> 1. CNのU+2018..2019, U+201C..201D がカギ括弧に化けているように見えますが、意図的でしょうか?

原ノ味 20220211 版のベースである SourceHanSerifCN 2.001, SourceHanSansCN 2.004 でもカギ括弧になっているように見えます。
SourceHanSerifReadMe.pdf 2.001 の p. 24 を見ると、どうも SourceHan が意図的にカギ括弧にしているようです。

> 2. CNとTWのU+301D..301Eがまともでないように見えるのはやむを得ない?

SourceHanSerif{CN|TW} 2.001, SourceHanSans{CN|TW} 2.004 とは違って見えるので、なぜ変わってしまっているのか確認します。

> 3. TWのU+FE59..FE5Eがまともでないように見えるのはやむを得ない?

SourceHanSerifTW 2.001, SourceHanSansTW 2.004 でも同じに見えるのでやむを得ないものと思います。

> 4. K1のU+3016..3019がまともでないように見えるのはやむを得ない?

SourceHanSerifKR 2.001, SourceHanSansKR 2.004 とは違って見えるので、なぜ変わってしまっているのか確認します。

```test.tex
% -*- coding: utf-8 mode:tex -*-

% For plain XeTeX

\nopagenumbers

\def\test{%
  \char"2018 \char"2019 \char"201C \char"201D \char"301D \char"301E \par
  \char"FE59 \char"FE5A \char"FE5B \char"FE5C \char"FE5D \char"FE5E \par
  \char"3016 \char"3017 \char"3018 \char"3019 \par
}

\font\fjp="[HaranoAjiMincho-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fsjp="[SourceHanSerifJP-Regular.otf]:vertical,+fwid,+vert" at 10pt

\font\fcn="[HaranoAjiMinchoCN-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fscn="[SourceHanSerifCN-Regular.otf]:vertical,+fwid,+vert" at 10pt

\font\ftw="[HaranoAjiMinchoTW-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fstw="[SourceHanSerifTW-Regular.otf]:vertical,+fwid,+vert" at 10pt

\font\fko="[HaranoAjiMinchoK1-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fskr="[SourceHanSerifKR-Regular.otf]:vertical,+fwid,+vert" at 10pt

\fjp HaranoAjiMincho-Reguar \par
\test
\fsjp SourceHanSerifJP-Reguar \par
\test

\vfill

\fcn HaranoAjiMinchoCN-Reguar \par
\test
\fscn SourceHanSerifCN-Reguar \par
\test

\vfill

\ftw HaranoAjiMinchoTW-Reguar \par
\test
\fstw SourceHanSerifTW-Reguar \par
\test

\vfill

\fko HaranoAjiMinchoK1-Reguar \par
\test
\fskr SourceHanSerifKR-Reguar \par
\test

\eject

\font\fjp="[HaranoAjiGothic-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fsjp="[SourceHanSansJP-Regular.otf]:vertical,+fwid,+vert" at 10pt

\font\fcn="[HaranoAjiGothicCN-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fscn="[SourceHanSansCN-Regular.otf]:vertical,+fwid,+vert" at 10pt

\font\ftw="[HaranoAjiGothicTW-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fstw="[SourceHanSansTW-Regular.otf]:vertical,+fwid,+vert" at 10pt

\font\fko="[HaranoAjiGothicK1-Regular.otf]:vertical,+fwid,+vert" at 10pt
\font\fskr="[SourceHanSansKR-Regular.otf]:vertical,+fwid,+vert" at 10pt

\fjp HaranoAjiGothic-Reguar \par
\test
\fsjp SourceHanSansJP-Reguar \par
\test

\vfill

\fcn HaranoAjiGothicCN-Reguar \par
\test
\fscn SourceHanSansCN-Reguar \par
\test

\vfill

\ftw HaranoAjiGothicTW-Reguar \par
\test
\fstw SourceHanSansTW-Reguar \par
\test

\vfill

\fko HaranoAjiGothicK1-Reguar \par
\test
\fskr SourceHanSansKR-Reguar \par
\test

\bye
```

**Comment by trueroad** [comment]
結論から申し上げますと 1., 2., 4. は仕様通りで問題なしです。3. だけ仕様からすると正しくないのですが縦組み用グリフを搭載していないため切り替えることができず「やむを得ない」ものとなります。

>> 2. CNとTWのU+301D..301Eがまともでないように見えるのはやむを得ない?
>
> SourceHanSerif{CN|TW} 2.001, SourceHanSans{CN|TW} 2.004 とは違って見えるので、なぜ変わってしまっているのか確認します。

下記の通り AG15, AC17 には U+301D, U+301E の縦組み用グリフが存在しません。
そのため原ノ味でも縦組み用に切り替わららず横組み用のグリフが使われますが、
AG15, AC17 仕様として「正しい」ということになります。

SourceHan は AI0 ですので AG15, AC17 の枠外で別途縦組み用グリフを用意して切り替えているものと思います。

CN:
UniGB-UTF32-V 1.007 を確認したところ U+301D と U+301E が存在しない（横組みと同じ CID を使う）ようです。
UniGB-UTF32-H 1.016 によると横組みの CID は

U+301D -> AG1 CID+9990
U+301E -> AG1 CID+9991

になっていますが、AG15 の GSUB である ag15-gsub.fea を見るとどちらの CID も存在しません。
よって AG15 には U+301D と U+301E の縦組み用グリフは存在しないものと思います。

TW:
UniCNS-UTF32-V 1.009 にも U+301D と U+301E が存在しないようです。
UniCNS-UTF32-H 1.019 では

U+301D -> AC1 CID+170
U+301E -> AC1 CID+171

で、やはり AC17 の GSUB である ac17-gsub.fea にはどちらもありません。
よって AC17 にも U+301D と U+301E の縦組み用グリフは存在しないものと思います。

>> 4. K1のU+3016..3019がまともでないように見えるのはやむを得ない?
>
> SourceHanSerifKR 2.001, SourceHanSansKR 2.004 とは違って見えるので、なぜ変わってしまっているのか確認します。

こちらも下記の通り AK12 には縦組み用グリフが存在しません。
そのため原ノ味でも縦組み用に切り替わららず横組み用のグリフが使われますが、
AK12 仕様として「正しい」ということになります。

SourceHan は AI0 ですので AK12 の枠外で別途縦組み用グリフを用意して切り替えているものと思います。

K1:
UniKS-UTF32-V 1.005 には U+3016, U+3017, U+3018, U+3019 いずれも存在しないようです。
UniKS-UTF32-H 1.008 では

U+3016 -> AK1 CID+8219
U+3017 -> AK1 CID+8220
U+3018 -> AK1 CID+8221
U+3019 -> AK1 CID+8222

になっており、AK12 の GSUB である ak12-gsub.txt にはいずれも存在しません。
よって AK12 には U+3016, U+3017, U+3018, U+3019 の縦組み用グリフは存在しないものと思います。

>> 1. CNのU+2018..2019, U+201C..201D がカギ括弧に化けているように見えますが、意図的でしょうか?
>
> 原ノ味 20220211 版のベースである SourceHanSerifCN 2.001, SourceHanSansCN 2.004 でもカギ括弧になっているように見えます。
> SourceHanSerifReadMe.pdf 2.001 の p. 24 を見ると、どうも SourceHan が意図的にカギ括弧にしているようです。

こちらですが、AG15 を確認すると 2. 4. とは違った興味深い状況で、
カギ括弧に化けるのが AG15 仕様上「正しい」ようです。

UniGB-UTF32-V 1.007 には U+2018, U+2019, U+201C, U+201D いずれも存在しません。
UniGB-UTF32-H 1.016 では

U+2018 -> AG1 CID+109
U+2019 -> AG1 CID+110
U+201C -> AG1 CID+111
U+201D -> AG1 CID+112

になっているのですが ag15-gsub.fea を見ると（UniGB-UTF32-V には無かったのに）いずれも vert が存在していて、

AG1 CID+109 -> AG1 CID+588
AG1 CID+110 -> AG1 CID+589
AG1 CID+111 -> AG1 CID+590
AG1 CID+112 -> AG1 CID+591

というように縦組み用グリフの CID が割り当てられています。
Adobe-GB1-5.pdf の CID 一覧でこれらを確認してみると、なんと縦組み用のカギ括弧になっています。
つまり AG15 の仕様として U+2018, U+2019, U+201C, U+201D の縦組み用グリフはカギ括弧になることが正しいということになるかと思います。

>> 3. TWのU+FE59..FE5Eがまともでないように見えるのはやむを得ない?
>
> SourceHanSerifTW 2.001, SourceHanSansTW 2.004 でも同じに見えるのでやむを得ないものと思います。

4 点ご指摘いただいたうち、これだけが AC17 仕様上「正しくない」ようです。
ただし、SourceHan が縦組み用グリフを搭載していないため原ノ味でも搭載できず「やむを得ない」状況です。

UniCNS-UTF32-V にはいずれも存在しません。
UniCNS-UTF32-H からは、

U+FE59 -> AC1 CID+160
U+FE5A -> AC1 CID+161
U+FE5B -> AC1 CID+162
U+FE5C -> AC1 CID+163
U+FE5D -> AC1 CID+164
U+FE5E -> AC1 CID+165

ac17-gsub.fea では（UniCNS-UTF32-V には無かったのに）いずれも vert が存在していて、

AC1 CID+160 -> AC1 CID+14111
AC1 CID+161 -> AC1 CID+14112
AC1 CID+162 -> AC1 CID+14113
AC1 CID+163 -> AC1 CID+14114
AC1 CID+164 -> AC1 CID+14115
AC1 CID+165 -> AC1 CID+14116

なのですが、HaranoAjiMinchoTW も HaranoAjiGothicTW も、AC1 CID+14111 ~ CID+14116 を搭載していません。
SourceHan でも縦組み用に切り替わらないということは、そもそもグリフを持っていないということなのでいたしかたありません。

**Comment by t-tk** [comment]
詳細な調査、ありがとうございました。
仕様もしくはグリフなしとのことを理解しました。
ここは閉じます。
