### ISSUE TITLE
Adobe-GB1-6

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFontsCN#2]
お世話になります。
今日初めて知ったのですが Adobe-GB1-6 が6月末に[出ていました](https://github.com/adobe-type-tools/cmap-resources/releases/tag/20230622)。

あまりよく分かっていないのですが
source-han-sans でグリフを持っている字もあるようです。
例えば、ニホニウム U+9FED 鿭  →  A-GB1-6 CID+30347
https://github.com/adobe-fonts/source-han-sans/blob/e3bfa7062185d1ec689b07b9236e108a9a00e9c5/Resources/utf32hw-cn.map#L30283C17-L30283C17

通用規範漢字表 2013年に入り、GB18030 に入っていなかった文字が Source Han Sans にすでに入っていたが、
2022年に GB18030 に入り 今回 Adobe-GBに入った運びなのかな、と思いました。(間違っているかもしれません)

そうすると、HaranoAjiFontsCN でも対応可能になったのではないか、と考えました。
ご対応を検討していただけないでしょうか。

**Comment by trueroad** [comment]
ありがとうございます。
まだ中身の確認ができておりませんが、先月 [source-han-serif 2.002](https://github.com/adobe-fonts/source-han-serif/releases/tag/2.002R) が出たようなので、そちらの対応とあわせて考えたいと思います。

**Comment by trueroad** [comment]
20231009 版で対応したつもりです
https://github.com/trueroad/HaranoAjiFontsCN/tree/20231009
ご確認ください

**Comment by t-tk** [comment]
ありがとうございました。
下記のように少々動作確認に手間取りましたが、Unicodeアクセス、CIDアクセスともばっちり出ました。

手元で動かない部分があったのですが、フォント側はバッチリで、japanese-otf-uptexの mlutf.sty のバグでした。実物のフォントがないと気づきにくく、今回のご対応が助けになりました。
こちらはもう少し清書して CTAN投稿する予定です。
https://github.com/t-tk/japanese-otf-uptex

**Comment by t-tk** [comment]
20231009 のリリースありがとうございました。
上記の私の japanese-otf-uptex は、mlutf.sty のバグではなく、手元のテストのバグでした。
現在全てテストは上手く動いています。
ここは閉じて大丈夫です。
